ALTER TABLE `icsl_ledars_prod`.`ref_lcda_wards` 
ADD UNIQUE INDEX `unq_ward_lcda_const` (`ward_name` ASC, `local_council_dev_area_id` ASC);

update ward_land_properties set property_valuation_status = 'SENT FOR VALUATION', last_updated_by_id = 1 where property_valuation_status = 'SENT';
update ward_land_properties set property_valuation_status = 'PENDING VALUATION', last_updated_by_id = 1 where property_valuation_status = 'PENDING';
update ward_land_properties set property_valuation_status = 'REQUIRE MODIFICATIONS', last_updated_by_id = 1 where property_valuation_status = 'RETURNED';
update ward_land_properties set property_valuation_status = 'APPROVED AND PROCESSED', last_updated_by_id = 1 where property_valuation_status = 'PROCESSED';

-- MySQL Workbench Synchronization
-- Generated: 2016-06-07 13:14
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: Samson Fagade

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `ref_geographical_boundaries` 
ADD COLUMN `inits_mapping` CHAR(5) NULL DEFAULT NULL AFTER `locale_code`;

ALTER TABLE `ref_person_titles` 
ADD COLUMN `inits_mapping` CHAR(5) NULL DEFAULT NULL AFTER `title_name`;

ALTER TABLE `ref_local_council_dev_area` 
ADD COLUMN `inits_mapping` CHAR(5) NULL DEFAULT NULL AFTER `lcda_chairman_id`;

ALTER TABLE `ref_commercial_types` 
ADD COLUMN `inits_mapping` CHAR(5) NULL DEFAULT NULL AFTER `commercial_type_name`;

ALTER TABLE `ref_residential_useages` 
ADD COLUMN `inits_mapping` CHAR(5) NULL DEFAULT NULL AFTER `residential_use_name`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 1 WHERE `boundary_name` = 'Albania';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 2 WHERE `boundary_name` = 'Algeria';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 3 WHERE `boundary_name` = 'American Samoa';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 4 WHERE `boundary_name` = 'Andorra';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 5 WHERE `boundary_name` = 'Angola';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 6 WHERE `boundary_name` = 'Anguilla';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 7 WHERE `boundary_name` = 'Antarctica';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 8 WHERE `boundary_name` = 'Antigua and Barbuda';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 9 WHERE `boundary_name` = 'Argentina';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 10 WHERE `boundary_name` = 'Armenia';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 11 WHERE `boundary_name` = 'Aruba';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 12 WHERE `boundary_name` = 'Australia';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 13 WHERE `boundary_name` = 'Austria';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 14 WHERE `boundary_name` = 'Azerbaijan';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 15 WHERE `boundary_name` = 'Bahamas, The';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 16 WHERE `boundary_name` = 'Bahrain';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 17 WHERE `boundary_name` = 'Bangladesh';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 18 WHERE `boundary_name` = 'Barbados';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 19 WHERE `boundary_name` = 'Belarus';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 20 WHERE `boundary_name` = 'Belgium';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 21 WHERE `boundary_name` = 'Belize';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 22 WHERE `boundary_name` = 'Benin';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 23 WHERE `boundary_name` = 'Bermuda';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 24 WHERE `boundary_name` = 'Bhutan';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 25 WHERE `boundary_name` = 'Bolivia';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 26 WHERE `boundary_name` = 'Bosnia and Herzegovina';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 27 WHERE `boundary_name` = 'Botswana';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 28 WHERE `boundary_name` = 'Bouvet Island';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 29 WHERE `boundary_name` = 'Brazil';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 30 WHERE `boundary_name` = 'British Indian Ocean Territory';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 31 WHERE `boundary_name` = 'Brunei';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 32 WHERE `boundary_name` = 'Bulgaria';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 33 WHERE `boundary_name` = 'Burkina Faso';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 34 WHERE `boundary_name` = 'Burundi';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 35 WHERE `boundary_name` = 'Cambodia';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 36 WHERE `boundary_name` = 'Cameroon';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 37 WHERE `boundary_name` = 'Canada';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 38 WHERE `boundary_name` = 'Cape Verde';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 39 WHERE `boundary_name` = 'Cayman Islands';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 40 WHERE `boundary_name` = 'Central African Republic';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 41 WHERE `boundary_name` = 'Chad';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 42 WHERE `boundary_name` = 'Chile';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 43 WHERE `boundary_name` = 'China';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 44 WHERE `boundary_name` = 'Christmas Island';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 45 WHERE `boundary_name` = 'Cocos (Keeling) Islands';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 46 WHERE `boundary_name` = 'Colombia';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 47 WHERE `boundary_name` = 'Comoros';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 48 WHERE `boundary_name` = 'Congo (DRC)';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 49 WHERE `boundary_name` = 'Cook Islands';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 50 WHERE `boundary_name` = 'Costa Rica';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 51 WHERE `boundary_name` = "Cote d'Ivoire";
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 52 WHERE `boundary_name` = 'Croatia';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 53 WHERE `boundary_name` = 'Cyprus';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 54 WHERE `boundary_name` = 'Czech Republic';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 55 WHERE `boundary_name` = 'Denmark';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 56 WHERE `boundary_name` = 'Djibouti';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 57 WHERE `boundary_name` = 'Dominica';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 58 WHERE `boundary_name` = 'Dominican Republic';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 59 WHERE `boundary_name` = 'East Timor';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 60 WHERE `boundary_name` = 'Ecuador';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 61 WHERE `boundary_name` = 'Egypt';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 62 WHERE `boundary_name` = 'El Salvador';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 63 WHERE `boundary_name` = 'Equatorial Guinea';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 64 WHERE `boundary_name` = 'Estonia';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 65 WHERE `boundary_name` = 'Ethiopia';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 66 WHERE `boundary_name` = 'Falkland Islands (Malvinas)';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 67 WHERE `boundary_name` = 'Faroe Islands';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 68 WHERE `boundary_name` = 'Fiji Islands';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 69 WHERE `boundary_name` = 'Finland';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 70 WHERE `boundary_name` = 'France';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 71 WHERE `boundary_name` = 'French Guiana';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 72 WHERE `boundary_name` = 'French Polynesia';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 73 WHERE `boundary_name` = 'French Southern and Antarctic ';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 74 WHERE `boundary_name` = 'Gabon';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 75 WHERE `boundary_name` = 'Gambia, The';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 76 WHERE `boundary_name` = 'Georgia';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 77 WHERE `boundary_name` = 'Germany';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 78 WHERE `boundary_name` = 'Ghana';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 79 WHERE `boundary_name` = 'Gibraltar';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 80 WHERE `boundary_name` = 'Greece';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 81 WHERE `boundary_name` = 'Greenland';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 82 WHERE `boundary_name` = 'Grenada';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 83 WHERE `boundary_name` = 'Guadeloupe';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 84 WHERE `boundary_name` = 'Guam';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 85 WHERE `boundary_name` = 'Guatemala';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 86 WHERE `boundary_name` = 'Guinea';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 87 WHERE `boundary_name` = 'Guinea-Bissau';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 88 WHERE `boundary_name` = 'Guyana';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 89 WHERE `boundary_name` = 'Haiti';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 90 WHERE `boundary_name` = 'Heard Island and McDonald Isla';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 91 WHERE `boundary_name` = 'Honduras';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 92 WHERE `boundary_name` = 'Hong Kong S.A.R.';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 93 WHERE `boundary_name` = 'Hungary';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 94 WHERE `boundary_name` = 'Iceland';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 95 WHERE `boundary_name` = 'India';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 96 WHERE `boundary_name` = 'Indonesia';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 97 WHERE `boundary_name` = 'Ireland';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 98 WHERE `boundary_name` = 'Israel';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 99 WHERE `boundary_name` = 'Italy';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 100 WHERE `boundary_name` = 'Jamaica';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 101 WHERE `boundary_name` = 'Japan';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 102 WHERE `boundary_name` = 'Jordan';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 103 WHERE `boundary_name` = 'Kazakhstan';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 104 WHERE `boundary_name` = 'Kenya';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 105 WHERE `boundary_name` = 'Kiribati';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 106 WHERE `boundary_name` = 'Korea';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 107 WHERE `boundary_name` = 'Kuwait';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 108 WHERE `boundary_name` = 'Kyrgyzstan';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 109 WHERE `boundary_name` = 'Laos';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 110 WHERE `boundary_name` = 'Latvia';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 111 WHERE `boundary_name` = 'Lebanon';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 112 WHERE `boundary_name` = 'Lesotho';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 113 WHERE `boundary_name` = 'Liberia';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 114 WHERE `boundary_name` = 'Liechtenstein';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 115 WHERE `boundary_name` = 'Lithuania';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 116 WHERE `boundary_name` = 'Luxembourg';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 117 WHERE `boundary_name` = 'Macau S.A.R.';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 118 WHERE `boundary_name` = 'Macedonia, Former Yugoslav Rep';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 119 WHERE `boundary_name` = 'Madagascar';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 120 WHERE `boundary_name` = 'Malawi';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 121 WHERE `boundary_name` = 'Malaysia';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 122 WHERE `boundary_name` = 'Maldives';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 123 WHERE `boundary_name` = 'Mali';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 124 WHERE `boundary_name` = 'Malta';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 125 WHERE `boundary_name` = 'Marshall Islands';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 126 WHERE `boundary_name` = 'Martinique';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 127 WHERE `boundary_name` = 'Mauritania';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 128 WHERE `boundary_name` = 'Mauritius';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 129 WHERE `boundary_name` = 'Mayotte';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 130 WHERE `boundary_name` = 'Mexico';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 131 WHERE `boundary_name` = 'Micronesia';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 132 WHERE `boundary_name` = 'Moldova';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 133 WHERE `boundary_name` = 'Monaco';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 134 WHERE `boundary_name` = 'Mongolia';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 135 WHERE `boundary_name` = 'Montserrat';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 136 WHERE `boundary_name` = 'Morocco';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 137 WHERE `boundary_name` = 'Mozambique';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 138 WHERE `boundary_name` = 'Myanmar';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 139 WHERE `boundary_name` = 'Namibia';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 140 WHERE `boundary_name` = 'Nauru';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 141 WHERE `boundary_name` = 'Nepal';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 142 WHERE `boundary_name` = 'Netherland Antilles';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 143 WHERE `boundary_name` = 'Netherlands, The';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 144 WHERE `boundary_name` = 'New Caledonia';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 145 WHERE `boundary_name` = 'New Zealand';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 146 WHERE `boundary_name` = 'Nicaragua';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 147 WHERE `boundary_name` = 'Niger';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 148 WHERE `boundary_name` = 'Nigeria';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 149 WHERE `boundary_name` = 'Niue';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 150 WHERE `boundary_name` = 'Norfolk Island';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 151 WHERE `boundary_name` = 'Northern Mariana Islands';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 152 WHERE `boundary_name` = 'Norway';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 153 WHERE `boundary_name` = 'Oman';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 154 WHERE `boundary_name` = 'Pakistan';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 155 WHERE `boundary_name` = 'Palau';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 156 WHERE `boundary_name` = 'Palestinian Authority';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 157 WHERE `boundary_name` = 'Panama';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 158 WHERE `boundary_name` = 'Papua New Guinea';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 159 WHERE `boundary_name` = 'Paraguay';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 160 WHERE `boundary_name` = 'Peru';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 161 WHERE `boundary_name` = 'Philippines';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 162 WHERE `boundary_name` = 'Pitcairn Islands';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 163 WHERE `boundary_name` = 'Poland';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 164 WHERE `boundary_name` = 'Portugal';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 165 WHERE `boundary_name` = 'Puerto Rico';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 166 WHERE `boundary_name` = 'Qatar';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 167 WHERE `boundary_name` = 'Reunion';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 168 WHERE `boundary_name` = 'Romania';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 169 WHERE `boundary_name` = 'Russia';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 170 WHERE `boundary_name` = 'Rwanda';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 171 WHERE `boundary_name` = 'Samoa';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 172 WHERE `boundary_name` = 'San Marino';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 173 WHERE `boundary_name` = 'Sao Tome and Principe';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 174 WHERE `boundary_name` = 'Saudi Arabia';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 175 WHERE `boundary_name` = 'Senegal';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 176 WHERE `boundary_name` = 'Seychelles';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 177 WHERE `boundary_name` = 'Sierra Leone';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 178 WHERE `boundary_name` = 'Singapore';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 179 WHERE `boundary_name` = 'Slovakia';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 180 WHERE `boundary_name` = 'Slovenia';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 181 WHERE `boundary_name` = 'Solomon Islands';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 182 WHERE `boundary_name` = 'Somalia';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 183 WHERE `boundary_name` = 'South Africa';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 184 WHERE `boundary_name` = 'South Georgia and the South Sa';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 185 WHERE `boundary_name` = 'South Korea';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 186 WHERE `boundary_name` = 'Spain';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 187 WHERE `boundary_name` = 'Sri Lanka';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 188 WHERE `boundary_name` = 'St. Helena';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 189 WHERE `boundary_name` = 'St. Kitts and Nevis';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 190 WHERE `boundary_name` = 'St. Lucia';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 191 WHERE `boundary_name` = 'St. Pierre and Miquelon';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 192 WHERE `boundary_name` = 'St. Vincent and the Grenadines';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 193 WHERE `boundary_name` = 'Suriname';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 194 WHERE `boundary_name` = 'Svalbard';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 195 WHERE `boundary_name` = 'Swaziland';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 196 WHERE `boundary_name` = 'Sweden';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 197 WHERE `boundary_name` = 'Switzerland';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 198 WHERE `boundary_name` = 'Taiwan';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 199 WHERE `boundary_name` = 'Tajikistan';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 200 WHERE `boundary_name` = 'Tanzania';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 201 WHERE `boundary_name` = 'Thailand';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 202 WHERE `boundary_name` = 'Togo';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 203 WHERE `boundary_name` = 'Tokelau';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 204 WHERE `boundary_name` = 'Tonga';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 205 WHERE `boundary_name` = 'Trinidad and Tobago';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 206 WHERE `boundary_name` = 'Tunisia';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 207 WHERE `boundary_name` = 'Turkey';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 208 WHERE `boundary_name` = 'Turkmenistan';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 209 WHERE `boundary_name` = 'Turks and Caicos Islands';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 210 WHERE `boundary_name` = 'Tuvalu';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 211 WHERE `boundary_name` = 'Uganda';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 212 WHERE `boundary_name` = 'Ukraine';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 213 WHERE `boundary_name` = 'United Arab Emirates';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 214 WHERE `boundary_name` = 'United Kingdom';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 215 WHERE `boundary_name` = 'United States';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 216 WHERE `boundary_name` = 'United States Minor Outlying I';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 217 WHERE `boundary_name` = 'Uruguay';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 218 WHERE `boundary_name` = 'Uzbekistan';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 219 WHERE `boundary_name` = 'Vanuatu';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 220 WHERE `boundary_name` = 'Vatican City';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 221 WHERE `boundary_name` = 'Venezuela';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 222 WHERE `boundary_name` = 'Vietnam';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 223 WHERE `boundary_name` = 'Virgin Islands (British)';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 224 WHERE `boundary_name` = 'Virgin Islands (U.S.)';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 225 WHERE `boundary_name` = 'Wallis and Futuna';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 226 WHERE `boundary_name` = 'Yemen';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 227 WHERE `boundary_name` = 'Yugoslavia';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 228 WHERE `boundary_name` = 'Zaire';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 229 WHERE `boundary_name` = 'Zambia';
UPDATE `ref_geographical_boundaries` SET `inits_mapping` = 230 WHERE `boundary_name` = 'Zimbabwe';


UPDATE `ref_geographical_boundaries` SET `inits_mapping`='15' WHERE `geographical_boundary_id`='11';
UPDATE `ref_geographical_boundaries` SET `inits_mapping`='26' WHERE `geographical_boundary_id`='21';
UPDATE `ref_geographical_boundaries` SET `inits_mapping`='33' WHERE `geographical_boundary_id`='26';
UPDATE `ref_geographical_boundaries` SET `inits_mapping`='48' WHERE `geographical_boundary_id`='37';
UPDATE `ref_geographical_boundaries` SET `boundary_name`='COSTA RICA', `inits_mapping`='50' WHERE `geographical_boundary_id`='38';
UPDATE `ref_geographical_boundaries` SET `boundary_name`='DOMINICAN REPUBLIC', `inits_mapping`='58' WHERE `geographical_boundary_id`='45';
UPDATE `ref_geographical_boundaries` SET `boundary_name`='FIJI ISLANDS', `inits_mapping`='68' WHERE `geographical_boundary_id`='52';
UPDATE `ref_geographical_boundaries` SET `inits_mapping`='75' WHERE `geographical_boundary_id`='56';
UPDATE `ref_geographical_boundaries` SET `inits_mapping`='118' WHERE `geographical_boundary_id`='89';
UPDATE `ref_geographical_boundaries` SET `inits_mapping`='143' WHERE `geographical_boundary_id`='157';
UPDATE `ref_geographical_boundaries` SET `inits_mapping`='210' WHERE `geographical_boundary_id`='198';
UPDATE `ref_geographical_boundaries` SET `inits_mapping`='219' WHERE `geographical_boundary_id`='206';


SELECT * FROM ref_geographical_boundaries;


UPDATE `ref_local_council_dev_area` SET  `inits_mapping` = 1 WHERE `lcda_name` = 'AGEGE';
UPDATE `ref_local_council_dev_area` SET  `inits_mapping` = 2 WHERE `lcda_name` = 'AJEROMI-IFELODUN';
UPDATE `ref_local_council_dev_area` SET  `inits_mapping` = 3 WHERE `lcda_name` = 'ALIMOSHO';
UPDATE `ref_local_council_dev_area` SET  `inits_mapping` = 4 WHERE `lcda_name` = 'AMUWO-ODOFIN';
UPDATE `ref_local_council_dev_area` SET  `inits_mapping` = 5 WHERE `lcda_name` = 'APAPA';
UPDATE `ref_local_council_dev_area` SET  `inits_mapping` = 6 WHERE `lcda_name` = 'BADAGRY';
UPDATE `ref_local_council_dev_area` SET  `inits_mapping` = 7 WHERE `lcda_name` = 'EPE';
UPDATE `ref_local_council_dev_area` SET  `inits_mapping` = 8 WHERE `lcda_name` = 'ETI-OSA';
UPDATE `ref_local_council_dev_area` SET  `inits_mapping` = 9 WHERE `lcda_name` = 'IBEJU-LEKKI';
UPDATE `ref_local_council_dev_area` SET  `inits_mapping` = 10 WHERE `lcda_name` = 'IFAKO-IJAYE';
UPDATE `ref_local_council_dev_area` SET  `inits_mapping` = 11 WHERE `lcda_name` = 'IKEJA';
UPDATE `ref_local_council_dev_area` SET  `inits_mapping` = 12 WHERE `lcda_name` = 'IKORODU';
UPDATE `ref_local_council_dev_area` SET  `inits_mapping` = 13 WHERE `lcda_name` = 'KOSOFE';
UPDATE `ref_local_council_dev_area` SET  `inits_mapping` = 14 WHERE `lcda_name` = 'LAGOS ISLAND';
UPDATE `ref_local_council_dev_area` SET  `inits_mapping` = 15 WHERE `lcda_name` = 'LAGOS MAINLAND';
UPDATE `ref_local_council_dev_area` SET  `inits_mapping` = 16 WHERE `lcda_name` = 'MUSHIN';
UPDATE `ref_local_council_dev_area` SET  `inits_mapping` = 17 WHERE `lcda_name` = 'OJO';
UPDATE `ref_local_council_dev_area` SET  `inits_mapping` = 18 WHERE `lcda_name` = 'OSHODI-ISOLO';
UPDATE `ref_local_council_dev_area` SET  `inits_mapping` = 19 WHERE `lcda_name` = 'SOMOLU';
UPDATE `ref_local_council_dev_area` SET  `inits_mapping` = 20 WHERE `lcda_name` = 'SURULERE';
UPDATE `ref_local_council_dev_area` SET `inits_mapping`='4' WHERE `local_council_dev_area_id`='6';
UPDATE `ref_local_council_dev_area` SET `inits_mapping`='19' WHERE `local_council_dev_area_id`='55';


SELECT * FROM ref_local_council_dev_area;

UPDATE `ref_person_titles` SET `inits_mapping` = 90 WHERE `title_name` = 'AIR CDRE';
UPDATE `ref_person_titles` SET `inits_mapping` = 105 WHERE `title_name` = 'AIR COMMODOR';
UPDATE `ref_person_titles` SET `inits_mapping` = 84 WHERE `title_name` = 'AIR MARSHAL';
UPDATE `ref_person_titles` SET `inits_mapping` = 3 WHERE `title_name` = 'ALFA';
UPDATE `ref_person_titles` SET `inits_mapping` = 1 WHERE `title_name` = 'ALHAJA';
UPDATE `ref_person_titles` SET `inits_mapping` = 2 WHERE `title_name` = 'ALHAJI';
UPDATE `ref_person_titles` SET `inits_mapping` = 18 WHERE `title_name` = 'ALHAJI';
UPDATE `ref_person_titles` SET `inits_mapping` = 74 WHERE `title_name` = 'ALHAJI AND MRS';
UPDATE `ref_person_titles` SET `inits_mapping` = 78 WHERE `title_name` = 'ALHAJI ALHAJA';
UPDATE `ref_person_titles` SET `inits_mapping` = 59 WHERE `title_name` = 'Ambassador ';
UPDATE `ref_person_titles` SET `inits_mapping` = 60 WHERE `title_name` = 'Apostle';
UPDATE `ref_person_titles` SET `inits_mapping` = 99 WHERE `title_name` = 'ARC';
UPDATE `ref_person_titles` SET `inits_mapping` = 4 WHERE `title_name` = 'ARCH';
UPDATE `ref_person_titles` SET `inits_mapping` = 91 WHERE `title_name` = 'ASIWAJU';
UPDATE `ref_person_titles` SET `inits_mapping` = 5 WHERE `title_name` = 'BARRISTER';
UPDATE `ref_person_titles` SET `inits_mapping` = 75 WHERE `title_name` = 'BISHOP';
UPDATE `ref_person_titles` SET `inits_mapping` = 92 WHERE `title_name` = 'BRIG. GENERAL';
UPDATE `ref_person_titles` SET `inits_mapping` = 6 WHERE `title_name` = 'CAPTAIN';
UPDATE `ref_person_titles` SET `inits_mapping` = 7 WHERE `title_name` = 'CHIEF';
UPDATE `ref_person_titles` SET `inits_mapping` = 8 WHERE `title_name` = 'CHIEF (MRS)';
UPDATE `ref_person_titles` SET `inits_mapping` = 64 WHERE `title_name` = 'Chief Dr';
UPDATE `ref_person_titles` SET `inits_mapping` = 48 WHERE `title_name` = 'CHIEF IMAM ';
UPDATE `ref_person_titles` SET `inits_mapping` = 93 WHERE `title_name` = 'CHIEF(MR)';
UPDATE `ref_person_titles` SET `inits_mapping` = 51 WHERE `title_name` = 'COL';
UPDATE `ref_person_titles` SET `inits_mapping` = 83 WHERE `title_name` = 'COMMANDER';
UPDATE `ref_person_titles` SET `inits_mapping` = 9 WHERE `title_name` = 'COMMODOR';
UPDATE `ref_person_titles` SET `inits_mapping` = 42 WHERE `title_name` = 'DEACON';
UPDATE `ref_person_titles` SET `inits_mapping` = 10 WHERE `title_name` = 'DEACONESS';
UPDATE `ref_person_titles` SET `inits_mapping` = 12 WHERE `title_name` = 'DR';
UPDATE `ref_person_titles` SET `inits_mapping` = 13 WHERE `title_name` = 'DR & MRS';
UPDATE `ref_person_titles` SET `inits_mapping` = 98 WHERE `title_name` = 'DR & MRS.';
UPDATE `ref_person_titles` SET `inits_mapping` = 89 WHERE `title_name` = 'DR.\/MRS';
UPDATE `ref_person_titles` SET `inits_mapping` = 14 WHERE `title_name` = 'ELDER';
UPDATE `ref_person_titles` SET `inits_mapping` = 15 WHERE `title_name` = 'ENGR';
UPDATE `ref_person_titles` SET `inits_mapping` = 16 WHERE `title_name` = 'ESQ';
UPDATE `ref_person_titles` SET `inits_mapping` = 17 WHERE `title_name` = 'EVANG';
UPDATE `ref_person_titles` SET `inits_mapping` = 68 WHERE `title_name` = 'GEN.';
UPDATE `ref_person_titles` SET `inits_mapping` = 69 WHERE `title_name` = 'HON.';
UPDATE `ref_person_titles` SET `inits_mapping` = 97 WHERE `title_name` = 'HON. (CHIEF)';
UPDATE `ref_person_titles` SET `inits_mapping` = 100 WHERE `title_name` = 'HON. (DR)';
UPDATE `ref_person_titles` SET `inits_mapping` = 19 WHERE `title_name` = 'HRH';
UPDATE `ref_person_titles` SET `inits_mapping` = 82 WHERE `title_name` = 'IMMAM';
UPDATE `ref_person_titles` SET `inits_mapping` = 63 WHERE `title_name` = 'Inspector';
UPDATE `ref_person_titles` SET `inits_mapping` = 20 WHERE `title_name` = 'JUSTICE';
UPDATE `ref_person_titles` SET `inits_mapping` = 21 WHERE `title_name` = 'LATE';
UPDATE `ref_person_titles` SET `inits_mapping` = 57 WHERE `title_name` = 'Late Alhaja';
UPDATE `ref_person_titles` SET `inits_mapping` = 56 WHERE `title_name` = 'Late Alhaji';
UPDATE `ref_person_titles` SET `inits_mapping` = 49 WHERE `title_name` = 'LATE CHIEF';
UPDATE `ref_person_titles` SET `inits_mapping` = 61 WHERE `title_name` = 'Late Dr.';
UPDATE `ref_person_titles` SET `inits_mapping` = 53 WHERE `title_name` = 'Late Madam';
UPDATE `ref_person_titles` SET `inits_mapping` = 46 WHERE `title_name` = 'LATE MR.';
UPDATE `ref_person_titles` SET `inits_mapping` = 81 WHERE `title_name` = 'LATE MR MRS';
UPDATE `ref_person_titles` SET `inits_mapping` = 47 WHERE `title_name` = 'LATE MRS.';
UPDATE `ref_person_titles` SET `inits_mapping` = 62 WHERE `title_name` = 'Late Pa';
UPDATE `ref_person_titles` SET `inits_mapping` = 71 WHERE `title_name` = 'LATE PRINCE';
UPDATE `ref_person_titles` SET `inits_mapping` = 22 WHERE `title_name` = 'LAWYER';
UPDATE `ref_person_titles` SET `inits_mapping` = 94 WHERE `title_name` = 'LT. COL';
UPDATE `ref_person_titles` SET `inits_mapping` = 96 WHERE `title_name` = 'LT. COL.(RTD)';
UPDATE `ref_person_titles` SET `inits_mapping` = 23 WHERE `title_name` = 'MADAM';
UPDATE `ref_person_titles` SET `inits_mapping` = 67 WHERE `title_name` = 'MAJOR';
UPDATE `ref_person_titles` SET `inits_mapping` = 24 WHERE `title_name` = 'MAJOR GEN';
UPDATE `ref_person_titles` SET `inits_mapping` = 77 WHERE `title_name` = 'MALLAM';
UPDATE `ref_person_titles` SET `inits_mapping` = 25 WHERE `title_name` = 'MISS';
UPDATE `ref_person_titles` SET `inits_mapping` = 26 WHERE `title_name` = 'MR & MRS';
UPDATE `ref_person_titles` SET `inits_mapping` = 27 WHERE `title_name` = 'MR.';
UPDATE `ref_person_titles` SET `inits_mapping` = 28 WHERE `title_name` = 'MRS.';
UPDATE `ref_person_titles` SET `inits_mapping` = 29 WHERE `title_name` = 'MS';
UPDATE `ref_person_titles` SET `inits_mapping` = 79 WHERE `title_name` = 'MWO';
UPDATE `ref_person_titles` SET `inits_mapping` = 40 WHERE `title_name` = 'N\/A';
UPDATE `ref_person_titles` SET `inits_mapping` = 76 WHERE `title_name` = 'OBA';
UPDATE `ref_person_titles` SET `inits_mapping` = 72 WHERE `title_name` = 'OLUWO';
UPDATE `ref_person_titles` SET `inits_mapping` = 30 WHERE `title_name` = 'OTUNBA';
UPDATE `ref_person_titles` SET `inits_mapping` = 31 WHERE `title_name` = 'PA';
UPDATE `ref_person_titles` SET `inits_mapping` = 32 WHERE `title_name` = 'PASTOR';
UPDATE `ref_person_titles` SET `inits_mapping` = 80 WHERE `title_name` = 'PASTOR MRS';
UPDATE `ref_person_titles` SET `inits_mapping` = 33 WHERE `title_name` = 'PHARMACIST';
UPDATE `ref_person_titles` SET `inits_mapping` = 34 WHERE `title_name` = 'PRINCE';
UPDATE `ref_person_titles` SET `inits_mapping` = 41 WHERE `title_name` = 'PRINCE';
UPDATE `ref_person_titles` SET `inits_mapping` = 45 WHERE `title_name` = 'PRINCESS';
UPDATE `ref_person_titles` SET `inits_mapping` = 35 WHERE `title_name` = 'PROF.';
UPDATE `ref_person_titles` SET `inits_mapping` = 43 WHERE `title_name` = 'PROPHET';
UPDATE `ref_person_titles` SET `inits_mapping` = 44 WHERE `title_name` = 'PROPHETESS';
UPDATE `ref_person_titles` SET `inits_mapping` = 36 WHERE `title_name` = 'REV';
UPDATE `ref_person_titles` SET `inits_mapping` = 70 WHERE `title_name` = 'REV. (MRS)';
UPDATE `ref_person_titles` SET `inits_mapping` = 37 WHERE `title_name` = 'REV. DR';
UPDATE `ref_person_titles` SET `inits_mapping` = 88 WHERE `title_name` = 'REV.\/MRS';
UPDATE `ref_person_titles` SET `inits_mapping` = 52 WHERE `title_name` = 'Rtd';
UPDATE `ref_person_titles` SET `inits_mapping` = 65 WHERE `title_name` = 'Rtd Major';
UPDATE `ref_person_titles` SET `inits_mapping` = 66 WHERE `title_name` = 'Rtd Navy';
UPDATE `ref_person_titles` SET `inits_mapping` = 103 WHERE `title_name` = 'RTD. AIR VICE MARSHAL';
UPDATE `ref_person_titles` SET `inits_mapping` = 38 WHERE `title_name` = 'RTD. GEN';
UPDATE `ref_person_titles` SET `inits_mapping` = 87 WHERE `title_name` = 'SENATOR';
UPDATE `ref_person_titles` SET `inits_mapping` = 39 WHERE `title_name` = 'SIR';
UPDATE `ref_person_titles` SET `inits_mapping` = 101 WHERE `title_name` = 'SNR APOSTLE';
UPDATE `ref_person_titles` SET `inits_mapping` = 73 WHERE `title_name` = 'SURVEYOR';
UPDATE `ref_person_titles` SET `inits_mapping` = 104 WHERE `title_name` = 'VEN.';
UPDATE `ref_person_titles` SET `inits_mapping` = 85 WHERE `title_name` = 'VISE AIR MARSHAL';
UPDATE `ref_person_titles` SET `inits_mapping` = 86 WHERE `title_name` = 'WING COMMANDER';
UPDATE `ref_person_titles` SET `inits_mapping`='12' WHERE `person_title_id`='2';
UPDATE `ref_person_titles` SET `inits_mapping`='69' WHERE `person_title_id`='4';
UPDATE `ref_person_titles` SET `inits_mapping`='29' WHERE `person_title_id`='9';
UPDATE `ref_person_titles` SET `inits_mapping`='15' WHERE `person_title_id`='13';
UPDATE `ref_person_titles` SET `inits_mapping`='26' WHERE `person_title_id`='19';
UPDATE `ref_person_titles` SET `inits_mapping`='8' WHERE `person_title_id`='20';
UPDATE `ref_person_titles` SET `inits_mapping`='38' WHERE `person_title_id`='22';


SELECT * FROM ref_person_titles;

UPDATE `ref_commercial_types` SET `inits_mapping` = 11 WHERE `commercial_type_name` = 'Abandoned Property';
UPDATE `ref_commercial_types` SET `inits_mapping` = 56 WHERE `commercial_type_name` = 'Abattoir';
UPDATE `ref_commercial_types` SET `inits_mapping` = 24 WHERE `commercial_type_name` = 'Bakery';
UPDATE `ref_commercial_types` SET `inits_mapping` = 15 WHERE `commercial_type_name` = 'Bank';
UPDATE `ref_commercial_types` SET `inits_mapping` = 27 WHERE `commercial_type_name` = "Boys' Quarters";
UPDATE `ref_commercial_types` SET `inits_mapping` = 30 WHERE `commercial_type_name` = 'Car Park';
UPDATE `ref_commercial_types` SET `inits_mapping` = 41 WHERE `commercial_type_name` = 'Car Sales Outlet';
UPDATE `ref_commercial_types` SET `inits_mapping` = 1 WHERE `commercial_type_name` = 'Commercial';
UPDATE `ref_commercial_types` SET `inits_mapping` = 62 WHERE `commercial_type_name` = 'Demolished';
UPDATE `ref_commercial_types` SET `inits_mapping` = 58 WHERE `commercial_type_name` = 'Dormitory Govt. Owned';
UPDATE `ref_commercial_types` SET `inits_mapping` = 42 WHERE `commercial_type_name` = 'Eatery';
UPDATE `ref_commercial_types` SET `inits_mapping` = 12 WHERE `commercial_type_name` = 'Education - Private School';
UPDATE `ref_commercial_types` SET `inits_mapping` = 13 WHERE `commercial_type_name` = 'Education - Public School';
UPDATE `ref_commercial_types` SET `inits_mapping` = 9 WHERE `commercial_type_name` = 'Educational';
UPDATE `ref_commercial_types` SET `inits_mapping` = 54 WHERE `commercial_type_name` = 'Embassy';
UPDATE `ref_commercial_types` SET `inits_mapping` = 43 WHERE `commercial_type_name` = 'Entertainment';
UPDATE `ref_commercial_types` SET `inits_mapping` = 47 WHERE `commercial_type_name` = 'Event Center';
UPDATE `ref_commercial_types` SET `inits_mapping` = 4 WHERE `commercial_type_name` = 'Exempted';
UPDATE `ref_commercial_types` SET `inits_mapping` = 33 WHERE `commercial_type_name` = 'Factory';
UPDATE `ref_commercial_types` SET `inits_mapping` = 45 WHERE `commercial_type_name` = 'Fish Pond';
UPDATE `ref_commercial_types` SET `inits_mapping` = 60 WHERE `commercial_type_name` = 'Garage';
UPDATE `ref_commercial_types` SET `inits_mapping` = 59 WHERE `commercial_type_name` = 'Generator Shed';
UPDATE `ref_commercial_types` SET `inits_mapping` = 34 WHERE `commercial_type_name` = 'Government Corporation e.g PHCN, NIPOST';
UPDATE `ref_commercial_types` SET `inits_mapping` = 29 WHERE `commercial_type_name` = 'Government Hospital';
UPDATE `ref_commercial_types` SET `inits_mapping` = 52 WHERE `commercial_type_name` = 'Government Revenue Generating Property E.g FIRS';
UPDATE `ref_commercial_types` SET `inits_mapping` = 44 WHERE `commercial_type_name` = 'Guard House ';
UPDATE `ref_commercial_types` SET `inits_mapping` = 25 WHERE `commercial_type_name` = 'Guest House';
UPDATE `ref_commercial_types` SET `inits_mapping` = 55 WHERE `commercial_type_name` = 'Horticulture Flower Gardens';
UPDATE `ref_commercial_types` SET `inits_mapping` = 26 WHERE `commercial_type_name` = 'Hospital';
UPDATE `ref_commercial_types` SET `inits_mapping` = 38 WHERE `commercial_type_name` = 'Hostels';
UPDATE `ref_commercial_types` SET `inits_mapping` = 22 WHERE `commercial_type_name` = 'Hotel';
UPDATE `ref_commercial_types` SET `inits_mapping` = 5 WHERE `commercial_type_name` = 'Industrial';
UPDATE `ref_commercial_types` SET `inits_mapping` = 48 WHERE `commercial_type_name` = 'Insurance Company ';
UPDATE `ref_commercial_types` SET `inits_mapping` = 20 WHERE `commercial_type_name` = 'Mechanic Workshop';
UPDATE `ref_commercial_types` SET `inits_mapping` = 64 WHERE `commercial_type_name` = 'NGO & Orphanages';
UPDATE `ref_commercial_types` SET `inits_mapping` = 21 WHERE `commercial_type_name` = 'Office';
UPDATE `ref_commercial_types` SET `inits_mapping` = 57 WHERE `commercial_type_name` = 'Oil and Gas Related Facility Plant and Terminal';
UPDATE `ref_commercial_types` SET `inits_mapping` = 10 WHERE `commercial_type_name` = 'Open\Empty Land';
UPDATE `ref_commercial_types` SET `inits_mapping` = 49 WHERE `commercial_type_name` = 'Other Financial Institution';
UPDATE `ref_commercial_types` SET `inits_mapping` = 39 WHERE `commercial_type_name` = 'Other Residential';
UPDATE `ref_commercial_types` SET `inits_mapping` = 3 WHERE `commercial_type_name` = 'Owner Occupied';
UPDATE `ref_commercial_types` SET `inits_mapping` = 7 WHERE `commercial_type_name` = 'Owner\/Tenant';
UPDATE `ref_commercial_types` SET `inits_mapping` = 16 WHERE `commercial_type_name` = 'Pensioner';
UPDATE `ref_commercial_types` SET `inits_mapping` = 36 WHERE `commercial_type_name` = 'Petrol Station';
UPDATE `ref_commercial_types` SET `inits_mapping` = 14 WHERE `commercial_type_name` = 'Place of Worship';
UPDATE `ref_commercial_types` SET `inits_mapping` = 32 WHERE `commercial_type_name` = 'Police Quarters';
UPDATE `ref_commercial_types` SET `inits_mapping` = 23 WHERE `commercial_type_name` = 'Poultry\/Meat Farm';
UPDATE `ref_commercial_types` SET `inits_mapping` = 53 WHERE `commercial_type_name` = 'Prison\/Correctional Facility';
UPDATE `ref_commercial_types` SET `inits_mapping` = 2 WHERE `commercial_type_name` = 'Residential (Corporate)';
UPDATE `ref_commercial_types` SET `inits_mapping` = 6 WHERE `commercial_type_name` = 'Residential (Revenue Generating)';
UPDATE `ref_commercial_types` SET `inits_mapping` = 40 WHERE `commercial_type_name` = 'Restaurant';
UPDATE `ref_commercial_types` SET `inits_mapping` = 63 WHERE `commercial_type_name` = 'Shed';
UPDATE `ref_commercial_types` SET `inits_mapping` = 18 WHERE `commercial_type_name` = 'Shop';
UPDATE `ref_commercial_types` SET `inits_mapping` = 19 WHERE `commercial_type_name` = 'Shopping Complex';
UPDATE `ref_commercial_types` SET `inits_mapping` = 51 WHERE `commercial_type_name` = 'Sports Club';
UPDATE `ref_commercial_types` SET `inits_mapping` = 61 WHERE `commercial_type_name` = 'Store';
UPDATE `ref_commercial_types` SET `inits_mapping` = 35 WHERE `commercial_type_name` = 'Supermarket';
UPDATE `ref_commercial_types` SET `inits_mapping` = 37 WHERE `commercial_type_name` = 'Telecommunication Facility';
UPDATE `ref_commercial_types` SET `inits_mapping` = 50 WHERE `commercial_type_name` = 'Theatre';
UPDATE `ref_commercial_types` SET `inits_mapping` = 31 WHERE `commercial_type_name` = 'Un-occupied';
UPDATE `ref_commercial_types` SET `inits_mapping` = 17 WHERE `commercial_type_name` = 'Under Construction';
UPDATE `ref_commercial_types` SET `inits_mapping` = 8 WHERE `commercial_type_name` = 'Unspecified';
UPDATE `ref_commercial_types` SET `inits_mapping` = 28 WHERE `commercial_type_name` = 'Ware-House';
UPDATE `ref_commercial_types` SET `inits_mapping` = 46 WHERE `commercial_type_name` = 'Workshop';
UPDATE `ref_commercial_types` SET `inits_mapping`='21' WHERE `commercial_type_id`='1';
UPDATE `ref_commercial_types` SET `inits_mapping`='34' WHERE `commercial_type_id`='28';
UPDATE `ref_commercial_types` SET `inits_mapping`='34' WHERE `commercial_type_id`='30';
UPDATE `ref_commercial_types` SET `inits_mapping`='55' WHERE `commercial_type_id`='32';
UPDATE `ref_commercial_types` SET `inits_mapping`='64' WHERE `commercial_type_id`='43';
UPDATE `ref_commercial_types` SET `inits_mapping`='57' WHERE `commercial_type_id`='45';
UPDATE `ref_commercial_types` SET `inits_mapping`='10' WHERE `commercial_type_id`='46';


SELECT * FROM ref_commercial_types;



UPDATE `ref_residential_useages` SET `inits_mapping` = 11 WHERE `residential_use_name` = 'Abandoned Property';
UPDATE `ref_residential_useages` SET `inits_mapping` = 56 WHERE `residential_use_name` = 'Abattoir';
UPDATE `ref_residential_useages` SET `inits_mapping` = 24 WHERE `residential_use_name` = 'Bakery';
UPDATE `ref_residential_useages` SET `inits_mapping` = 15 WHERE `residential_use_name` = 'Bank';
UPDATE `ref_residential_useages` SET `inits_mapping` = 27 WHERE `residential_use_name` = "Boys' Quarters";
UPDATE `ref_residential_useages` SET `inits_mapping` = 30 WHERE `residential_use_name` = 'Car Park';
UPDATE `ref_residential_useages` SET `inits_mapping` = 41 WHERE `residential_use_name` = 'Car Sales Outlet';
UPDATE `ref_residential_useages` SET `inits_mapping` = 1 WHERE `residential_use_name` = 'Commercial';
UPDATE `ref_residential_useages` SET `inits_mapping` = 62 WHERE `residential_use_name` = 'Demolished';
UPDATE `ref_residential_useages` SET `inits_mapping` = 58 WHERE `residential_use_name` = 'Dormitory Govt. Owned';
UPDATE `ref_residential_useages` SET `inits_mapping` = 42 WHERE `residential_use_name` = 'Eatery';
UPDATE `ref_residential_useages` SET `inits_mapping` = 12 WHERE `residential_use_name` = 'Education - Private School';
UPDATE `ref_residential_useages` SET `inits_mapping` = 13 WHERE `residential_use_name` = 'Education - Public School';
UPDATE `ref_residential_useages` SET `inits_mapping` = 9 WHERE `residential_use_name` = 'Educational';
UPDATE `ref_residential_useages` SET `inits_mapping` = 54 WHERE `residential_use_name` = 'Embassy';
UPDATE `ref_residential_useages` SET `inits_mapping` = 43 WHERE `residential_use_name` = 'Entertainment';
UPDATE `ref_residential_useages` SET `inits_mapping` = 47 WHERE `residential_use_name` = 'Event Center';
UPDATE `ref_residential_useages` SET `inits_mapping` = 4 WHERE `residential_use_name` = 'Exempted';
UPDATE `ref_residential_useages` SET `inits_mapping` = 33 WHERE `residential_use_name` = 'Factory';
UPDATE `ref_residential_useages` SET `inits_mapping` = 45 WHERE `residential_use_name` = 'Fish Pond';
UPDATE `ref_residential_useages` SET `inits_mapping` = 60 WHERE `residential_use_name` = 'Garage';
UPDATE `ref_residential_useages` SET `inits_mapping` = 59 WHERE `residential_use_name` = 'Generator Shed';
UPDATE `ref_residential_useages` SET `inits_mapping` = 34 WHERE `residential_use_name` = 'Government Corporation e.g PHCN, NIPOST';
UPDATE `ref_residential_useages` SET `inits_mapping` = 29 WHERE `residential_use_name` = 'Government Hospital';
UPDATE `ref_residential_useages` SET `inits_mapping` = 52 WHERE `residential_use_name` = 'Government Revenue Generating Property E.g FIRS';
UPDATE `ref_residential_useages` SET `inits_mapping` = 44 WHERE `residential_use_name` = 'Guard House ';
UPDATE `ref_residential_useages` SET `inits_mapping` = 25 WHERE `residential_use_name` = 'Guest House';
UPDATE `ref_residential_useages` SET `inits_mapping` = 55 WHERE `residential_use_name` = 'Horticulture\/Flower Gardens';
UPDATE `ref_residential_useages` SET `inits_mapping` = 26 WHERE `residential_use_name` = 'Hospital';
UPDATE `ref_residential_useages` SET `inits_mapping` = 38 WHERE `residential_use_name` = 'Hostels';
UPDATE `ref_residential_useages` SET `inits_mapping` = 22 WHERE `residential_use_name` = 'Hotel';
UPDATE `ref_residential_useages` SET `inits_mapping` = 5 WHERE `residential_use_name` = 'Industrial';
UPDATE `ref_residential_useages` SET `inits_mapping` = 48 WHERE `residential_use_name` = 'Insurance Company ';
UPDATE `ref_residential_useages` SET `inits_mapping` = 20 WHERE `residential_use_name` = 'Mechanic Workshop';
UPDATE `ref_residential_useages` SET `inits_mapping` = 64 WHERE `residential_use_name` = 'NGO & Orphanages';
UPDATE `ref_residential_useages` SET `inits_mapping` = 21 WHERE `residential_use_name` = 'Office';
UPDATE `ref_residential_useages` SET `inits_mapping` = 57 WHERE `residential_use_name` = 'Oil and Gas Related Facility Plant and Terminal';
UPDATE `ref_residential_useages` SET `inits_mapping` = 10 WHERE `residential_use_name` = 'Open\/Empty Land';
UPDATE `ref_residential_useages` SET `inits_mapping` = 49 WHERE `residential_use_name` = 'Other Financial Institution';
UPDATE `ref_residential_useages` SET `inits_mapping` = 39 WHERE `residential_use_name` = 'Other Residential';
UPDATE `ref_residential_useages` SET `inits_mapping` = 3 WHERE `residential_use_name` = 'Owner Occupied';
UPDATE `ref_residential_useages` SET `inits_mapping` = 7 WHERE `residential_use_name` = 'Owner\/Tenant';
UPDATE `ref_residential_useages` SET `inits_mapping` = 16 WHERE `residential_use_name` = 'Pensioner';
UPDATE `ref_residential_useages` SET `inits_mapping` = 36 WHERE `residential_use_name` = 'Petrol Station';
UPDATE `ref_residential_useages` SET `inits_mapping` = 14 WHERE `residential_use_name` = 'Place of Worship';
UPDATE `ref_residential_useages` SET `inits_mapping` = 32 WHERE `residential_use_name` = 'Police Quarters';
UPDATE `ref_residential_useages` SET `inits_mapping` = 23 WHERE `residential_use_name` = 'Poultry\/Meat Farm';
UPDATE `ref_residential_useages` SET `inits_mapping` = 53 WHERE `residential_use_name` = 'Prison\/Correctional Facility';
UPDATE `ref_residential_useages` SET `inits_mapping` = 2 WHERE `residential_use_name` = 'Residential (Corporate)';
UPDATE `ref_residential_useages` SET `inits_mapping` = 6 WHERE `residential_use_name` = 'Residential (Revenue Generating)';
UPDATE `ref_residential_useages` SET `inits_mapping` = 40 WHERE `residential_use_name` = 'Restaurant';
UPDATE `ref_residential_useages` SET `inits_mapping` = 63 WHERE `residential_use_name` = 'Shed';
UPDATE `ref_residential_useages` SET `inits_mapping` = 18 WHERE `residential_use_name` = 'Shop';
UPDATE `ref_residential_useages` SET `inits_mapping` = 19 WHERE `residential_use_name` = 'Shopping Complex';
UPDATE `ref_residential_useages` SET `inits_mapping` = 51 WHERE `residential_use_name` = 'Sports Club';
UPDATE `ref_residential_useages` SET `inits_mapping` = 61 WHERE `residential_use_name` = 'Store';
UPDATE `ref_residential_useages` SET `inits_mapping` = 35 WHERE `residential_use_name` = 'Supermarket';
UPDATE `ref_residential_useages` SET `inits_mapping` = 37 WHERE `residential_use_name` = 'Telecommunication Facility';
UPDATE `ref_residential_useages` SET `inits_mapping` = 50 WHERE `residential_use_name` = 'Theatre';
UPDATE `ref_residential_useages` SET `inits_mapping` = 31 WHERE `residential_use_name` = 'Un-occupied';
UPDATE `ref_residential_useages` SET `inits_mapping` = 17 WHERE `residential_use_name` = 'Under Construction';
UPDATE `ref_residential_useages` SET `inits_mapping` = 8 WHERE `residential_use_name` = 'Unspecified';
UPDATE `ref_residential_useages` SET `inits_mapping` = 28 WHERE `residential_use_name` = 'Ware-House';
UPDATE `ref_residential_useages` SET `inits_mapping` = 46 WHERE `residential_use_name` = 'Workshop';
UPDATE `ref_residential_useages` SET `inits_mapping`='6' WHERE `residential_use_id`='7';



SELECT * FROM icsl_ledars_db.ref_residential_useages;

-- MySQL Workbench Synchronization
-- Generated: 2016-06-07 15:21
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: Samson Fagade

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `property_qualities` 
ADD COLUMN `inits_mapping` CHAR(5) NULL DEFAULT NULL AFTER `percentage_value`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


UPDATE `property_qualities` SET `inits_mapping` = 1 WHERE concat(`quality_name`,' ',`percentage_value`) = 'Low 0.5';
UPDATE `property_qualities` SET `inits_mapping` = 2 WHERE concat(`quality_name`,' ',`percentage_value`) = 'Medium 0.75';
UPDATE `property_qualities` SET `inits_mapping` = 3 WHERE concat(`quality_name`,' ',`percentage_value`) = 'High 1.0';
UPDATE `property_qualities` SET `inits_mapping` = 0 WHERE concat(`quality_name`,' ',`percentage_value`) = 'Missing PCR';
UPDATE `property_qualities` SET `inits_mapping` = 6 WHERE concat(`quality_name`,' ',`percentage_value`) = 'Low 0.2';
UPDATE `property_qualities` SET `inits_mapping` = 7 WHERE concat(`quality_name`,' ',`percentage_value`) = 'Low 0.3';
UPDATE `property_qualities` SET `inits_mapping` = 8 WHERE concat(`quality_name`,' ',`percentage_value`) = 'Low 0.4';
UPDATE `property_qualities` SET `inits_mapping` = 10 WHERE concat(`quality_name`,' ',`percentage_value`) = 'Medium 0.60';
UPDATE `property_qualities` SET `inits_mapping` = 11 WHERE concat(`quality_name`,' ',`percentage_value`) = 'Medium 0.65';
UPDATE `property_qualities` SET `inits_mapping` = 12 WHERE concat(`quality_name`,' ',`percentage_value`) = 'Medium 0.70';
UPDATE `property_qualities` SET `inits_mapping` = 14 WHERE concat(`quality_name`,' ',`percentage_value`) = 'High 0.8';
UPDATE `property_qualities` SET `inits_mapping` = 15 WHERE concat(`quality_name`,' ',`percentage_value`) = 'High 0.85';
UPDATE `property_qualities` SET `inits_mapping` = 16 WHERE concat(`quality_name`,' ',`percentage_value`) = 'High 0.90';
UPDATE `property_qualities` SET `inits_mapping` = 17 WHERE concat(`quality_name`,' ',`percentage_value`) = 'High 0.95';
UPDATE `property_qualities` SET `inits_mapping` = 18 WHERE concat(`quality_name`,' ',`percentage_value`) = 'High 0.99';
UPDATE `property_qualities` SET `inits_mapping` = 20 WHERE concat(`quality_name`,' ',`percentage_value`) = 'Medium 0.55';
UPDATE `property_qualities` SET `inits_mapping` = 21 WHERE concat(`quality_name`,' ',`percentage_value`) = 'Medium 0.68';
UPDATE `property_qualities` SET `inits_mapping` = 22 WHERE concat(`quality_name`,' ',`percentage_value`) = 'Medium 0.58';
UPDATE `property_qualities` SET `inits_mapping` = 23 WHERE concat(`quality_name`,' ',`percentage_value`) = 'Low 0.38';
UPDATE `property_qualities` SET `inits_mapping` = 24 WHERE concat(`quality_name`,' ',`percentage_value`) = 'Low 0.10';
UPDATE `property_qualities` SET `inits_mapping` = 25 WHERE concat(`quality_name`,' ',`percentage_value`) = 'High 0.98';
UPDATE `property_qualities` SET `inits_mapping` = 26 WHERE concat(`quality_name`,' ',`percentage_value`) = 'High 0.94';
UPDATE `property_qualities` SET `inits_mapping` = 27 WHERE concat(`quality_name`,' ',`percentage_value`) = 'High 0.96';
UPDATE `property_qualities` SET `inits_mapping` = 28 WHERE concat(`quality_name`,' ',`percentage_value`) = 'Low 0.35';
UPDATE `property_qualities` SET `inits_mapping` = 29 WHERE concat(`quality_name`,' ',`percentage_value`) = 'High 1.0';
UPDATE `property_qualities` SET `inits_mapping` = 30 WHERE concat(`quality_name`,' ',`percentage_value`) = 'Low 0.25';
UPDATE `property_qualities` SET `inits_mapping` = 31 WHERE concat(`quality_name`,' ',`percentage_value`) = 'Medium 0.66';
UPDATE `property_qualities` SET `inits_mapping` = 32 WHERE concat(`quality_name`,' ',`percentage_value`) = 'Low 0.45';
UPDATE `property_qualities` SET `inits_mapping` = 33 WHERE concat(`quality_name`,' ',`percentage_value`) = 'High 0.97';
UPDATE `property_qualities` SET `inits_mapping` = 34 WHERE concat(`quality_name`,' ',`percentage_value`) = 'Medium';
UPDATE `property_qualities` SET `inits_mapping` = 35 WHERE concat(`quality_name`,' ',`percentage_value`) = 'Medium';
UPDATE `property_qualities` SET `inits_mapping` = 36 WHERE concat(`quality_name`,' ',`percentage_value`) = 'Medium 0.56';
UPDATE `property_qualities` SET `inits_mapping` = 37 WHERE concat(`quality_name`,' ',`percentage_value`) = 'high';
UPDATE `property_qualities` SET `inits_mapping` = 38 WHERE concat(`quality_name`,' ',`percentage_value`) = 'High';
UPDATE `property_qualities` SET `inits_mapping` = 39 WHERE concat(`quality_name`,' ',`percentage_value`) = 'High';
UPDATE `property_qualities` SET `inits_mapping` = 40 WHERE concat(`quality_name`,' ',`percentage_value`) = 'High';
UPDATE `property_qualities` SET `inits_mapping` = 41 WHERE concat(`quality_name`,' ',`percentage_value`) = 'High 0.84';
UPDATE `property_qualities` SET `inits_mapping`='37' WHERE `property_quality_id`='1';
UPDATE `property_qualities` SET `inits_mapping`='16' WHERE `property_quality_id`='5';
UPDATE `property_qualities` SET `inits_mapping`='3' WHERE `property_quality_id`='12';
UPDATE `property_qualities` SET `inits_mapping`='24' WHERE `property_quality_id`='13';
UPDATE `property_qualities` SET `inits_mapping`='34' WHERE `property_quality_id`='22';
UPDATE `property_qualities` SET `inits_mapping`='10' WHERE `property_quality_id`='26';
UPDATE `property_qualities` SET `inits_mapping`='12' WHERE `property_quality_id`='30';



SELECT * FROM property_qualities;

