package net.icsl.ledar.web.rest;

import java.util.Set;

import javax.ws.rs.ApplicationPath;
import javax.ws.rs.core.Application;

/**
 * @author sfagade
 * @date Nov 20, 2015
 */
@ApplicationPath("/rest")
public class JaxRsActivator extends Application {

    @Override
    public Set<Class<?>> getClasses() {
        Set<Class<?>> resources = new java.util.HashSet<>();
        addRestResourceClasses(resources);
        return resources;
    }

    /**
     * Do not modify addRestResourceClasses() method. It is automatically
     * re-generated by NetBeans REST support to populate given list with all
     * resources defined in the project.
     */
    private void addRestResourceClasses(Set<Class<?>> resources) {
        resources.add(net.icsl.ledar.web.authentication.AuthenticationRestService.class);
        resources.add(net.icsl.ledar.web.rest.PropertyRestService.class);
        resources.add(net.icsl.ledar.web.rest.ReferenceRestService.class);
        resources.add(net.icsl.ledar.web.rest.SearchRestService.class);
    }

}
